package:
    name: nrel-osos
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - NREL-rex
    - numpy
    - pandas
    - pypistats
    - requests
  run:
    - python
    - pip
    - NREL-rex
    - numpy
    - pandas
    - pypistats
    - requests

about:
  home: "https://github.com/NREL/osos"
  license: BSD 3-Clause
  summary: "Open Source Ops and Statistics (OSOS)"
  doc_url: "https://nrel.github.io/osos"
  dev_url: "https://github.com/NREL/osos"
