# This workflow updates osos data every week

name: Update OSOS Data
on:

  # Run every monday at 8am Mountain Time (14 UTC)
  schedule:
    - cron: "0 14 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - name: Checkout OSOS
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Checkout and rebase data branch
        run: |
          git checkout nrel_osos_data
          git rebase main

      - name: make a test file
        run: |
          touch ./data/test.csv

          #      - name: Run the OSOS CLI
          #        run: |
          #          osos --config ./osos_config.csv -v

      - name: Set credentials and push
        run: |
          git config --global user.name 'grantbuster'
          git config --global user.email 'grant.buster@nrel.gov'
          git add ./data/*.csv
          git commit -m "update osos data"
          git push --force
