# This workflow updates osos data every week

name: Update OSOS Data
on:

  # Run every monday at 8am Mountain Time (14 UTC)
  schedule:
    - cron: "0 14 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - name: Checkout OSOS
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run the OSOS CLI
        run: |
          osos --config ./osos_config.csv -v

      - name: Push data
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}
        with:
          add: "./data/*.csv"
          message: Update OSOS Data
          author_name: GitHub Actions
          author_email: actions@github.com
          committer_name: GitHub Actions
          committer_email: actions@github.com
